
on:
  workflow_dispatch:
    branches: [ "main" ]
    inputs:
      environment:
        description: "Deployment environment"
        required: true
        default: "develop"
        type: choice
        options:
          - develop
          - staging
          - production

jobs:
  build_new_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 

      - name: print hello
        run: echo "hello world in ${{ inputs.environment }} environment"
  Second_step:
    runs-on: ubuntu-latest
    steps:
      - name: print second step
        run: echo "This is the second step in ${{ inputs.environment }} environment"