
on:
  workflow_dispatch:
    branches: [ "main" ]
    inputs:
      environment:
        description: "Deployment environment"
        required: true
        default: "develop"
        type: choice
        options:
          - develop
          - staging
          - production

jobs:
  build_new_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 
      
      - name: github context print
        run: echo "${{ toJson(github) }}"
      
      - name: job context print
        run: echo "${{ toJson(job) }}"
      
      - name : step context print
        run: echo "${{ toJson(steps) }}"